config/routes.rb
ChouetteSocial::Application.routes.draw do

  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index] do
    collection do
      get 'test'
      post 'newfeedpost'
      get 'newfeedpost'
      post 'setwallpaper'
      get 'setwallpaper'
    end
  end
  
  resources :feedposts, :only => [:index] do
    collection do
      post 'add_new'
      get 'add_new'
    end
  end

  root :to => "users#index"
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user

  attr_accessible :provider, :uid, :uname, :uemail, :token, :token_secret, :token_refresh, :sf_consumer_key, :sf_consumer_secret
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!, :except => [:create, :signin, :signup, :newaccount, :failure]
  
  protect_from_forgery :except => :create     # https://github.com/intridea/omniauth/issues/203


  # GET all authentication services assigned to the current user
  def index
    @services = current_user.services.order('provider asc')
  end

  # POST to remove an authentication service
  def destroy
    # remove an authentication service linked to the current user
    @service = current_user.services.find(params[:id])
    
    if session[:service_id] == @service.id
      flash[:error] = 'You are currently signed in with this account!'
    else
      @service.destroy
    end
    
    redirect_to services_path
  end

  # POST from signup view
  def newaccount
    if params[:commit] == "Cancel"
      session[:authhash] = nil
      session.delete :authhash
      redirect_to root_url
    else  # create account
      @newuser = User.new
      @newuser.name = session[:authhash][:name]
      @newuser.email = session[:authhash][:email]
      @newuser.services.build(
        :provider => session[:authhash][:provider],
        :uid => session[:authhash][:uid],
        :uname => session[:authhash][:name],
        :uemail => session[:authhash][:email],
        :token => session[:authhash][:token],
        :token_secret => session[:authhash][:token_secret],
        :token_refresh => session[:authhash][:token_refresh],
        :sf_consumer_key => session[:authhash][:sf_consumer_key],
        :sf_consumer_secret => session[:authhash][:sf_consumer_secret]
      )
      logger.info("---> New User created with service. #{session[:authhash][:provider]}")

      if @newuser.save!
        # signin existing user
        # in the session his user id and the service id used for signing in is stored
        session[:user_id] = @newuser.id
        session[:service_id] = @newuser.services.first.id
        
        flash[:notice] = 'Your account has been created and you have been signed in!'
        redirect_to root_url
      else
        flash[:error] = 'This is embarrassing! There was an error while creating your account from which we were not able to recover.'
        redirect_to root_url
      end  
    end
  end  
  
  # Sign out current user
  def signout 
    if current_user
      session[:user_id] = nil
      session[:service_id] = nil
      session.delete :user_id
      session.delete :service_id
      flash[:notice] = 'You have been signed out!'
    end  
    redirect_to root_url
  end
  
  # callback: success
  # This handles signing in and adding an authentication service to existing accounts itself
  # It renders a separate view if there is a new user to create
  def create
    # get the service parameter from the Rails router
    params[:service] ? service_route = params[:service] : service_route = 'No service recognized (invalid callback)'

    # get the full hash from omniauth
    omniauth = request.env['omniauth.auth']
    
    # continue only if hash and parameter exist
    if omniauth and params[:service]

      # map the returned hashes to our variables first - the hashes differs for every service
      
      # create a new hash
      @authhash = Hash.new
      
      if service_route == 'facebook'
        omniauth['extra']['user_hash']['email'] ? @authhash[:email] =  omniauth['extra']['user_hash']['email'] : @authhash[:email] = ''
        omniauth['extra']['user_hash']['name'] ? @authhash[:name] =  omniauth['extra']['user_hash']['name'] : @authhash[:name] = ''
        omniauth['extra']['user_hash']['id'] ?  @authhash[:uid] =  omniauth['extra']['user_hash']['id'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] = omniauth['provider'] : @authhash[:provider] = ''
        omniauth['credentials']['token'] ? @authhash[:token] = omniauth['credentials']['token'] : @authhash[:token] = ''

        omniauth['credentials']['token'] ? @authhash[:token] = omniauth['credentials']['token'] : @authhash[:token] = ''
        # Facebook do not use secret. It is perpetual based on offline_access
        @authhash[:token_secret] = ''
        # sf_cs, token_refresh, and sf_ck are only for chatter
        @authhash[:sf_consumer_key] = ''
        @authhash[:sf_consumer_secret] = ''
        @authhash[:token_refresh] = ''
        
      elsif service_route == 'linked_in'
        omniauth['user_info']['email'] ? @authhash[:email] =  omniauth['user_info']['email'] : @authhash[:email] = ''
        omniauth['user_info']['name'] ? @authhash[:name] =  omniauth['user_info']['name'] : @authhash[:name] = ''
        omniauth['uid'] ? @authhash[:uid] = omniauth['uid'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] =  omniauth['provider'] : @authhash[:provider] = ''

        omniauth['credentials']['token'] ? @authhash[:token] = omniauth['credentials']['token'] : @authhash[:token] = ''
        omniauth['credentials']['secret'] ? @authhash[:token_secret] = omniauth['credentials']['secret'] : @authhash[:token_secret] = ''
        # sf_cs, token_refresh, and sf_ck are only for chatter
        @authhash[:sf_consumer_key] = ''
        @authhash[:sf_consumer_secret] = ''
        @authhash[:token_refresh] = ''

      elsif service_route == 'chatter' || service_route == 'forcedotcom'
        omniauth['user_info']['email'] ? @authhash[:email] =  omniauth['user_info']['email'] : @authhash[:email] = ''
        omniauth['user_info']['name'] ? @authhash[:name] =  omniauth['user_info']['name'] : @authhash[:name] = ''
        omniauth['extra']['user_hash']['user_id'] ? @authhash[:uid] =  omniauth['extra']['user_hash']['user_id'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] =  omniauth['provider'] : @authhash[:provider] = ''
        # note Salesforce's refresh-token is not stored on the omniauth tree, it is instead at
        # request.env['omniauth.strategy'].instance_variable_get(:@access_token).instance_variable_get(:@refresh_token)
        # Furthermore, due to time-out, Force.com's token is session based and does not last forever.
        # You need to use refresh_token to regenerate the access_token
        # @authhash[:token_refresh] = request.env['omniauth.strategy'].instance_variable_get(:@access_token).instance_variable_get(:@refresh_token)
        # @authhash[:sf_consumer_key] = request.env['omniauth.strategy'].instance_variable_get(:@access_token).client.id
        # @authhash[:sf_consumer_secret] = request.env['omniauth.strategy'].instance_variable_get(:@access_token).client.secret

        @authhash[:token] = omniauth['credentials']['token']
        @authhash[:token_secret] = '' #Not used only for LinkedIn / Twitter
        @authhash[:token_refresh] = omniauth['credentials']['refresh_token']
        @authhash[:sf_consumer_key] = omniauth['credentials']['consumer_key']
        @authhash[:sf_consumer_secret] = omniauth['credentials']['consumer_secret']
      elsif service_route == 'twitter'
        omniauth['user_info']['email'] ? @authhash[:email] =  omniauth['user_info']['email'] : @authhash[:email] = ''
        omniauth['user_info']['name'] ? @authhash[:name] =  omniauth['user_info']['name'] : @authhash[:name] = ''
        omniauth['uid'] ? @authhash[:uid] = omniauth['uid'].to_s : @authhash[:uid] = ''
        omniauth['provider'] ? @authhash[:provider] = omniauth['provider'] : @authhash[:provider] = ''

        omniauth['credentials']['token'] ? @authhash[:token] = omniauth['credentials']['token'] : @authhash[:token] = ''
        omniauth['credentials']['secret'] ? @authhash[:token_secret] = omniauth['credentials']['secret'] : @authhash[:token_secret] = ''
        # sf_cs, token_refresh, and sf_ck are only for chatter
        @authhash[:sf_consumer_key] = ''
        @authhash[:sf_consumer_secret] = ''
        @authhash[:token_refresh] = ''

      else        
        # debug to output the hash that has been returned when adding new services
        render :text => omniauth.to_yaml
        return
      end 
      
      if @authhash[:uid] != '' and @authhash[:provider] != ''
        
        auth = Service.find_by_provider_and_uid(@authhash[:provider], @authhash[:uid])

        # if the user is currently signed in, he/she might want to add another account to signin
        if user_signed_in?
          if auth
            flash[:notice] = 'Your account at ' + @authhash[:provider].capitalize + ' is already connected with this site.'
            redirect_to services_path
          else
            current_user.services.create!(
              :provider => @authhash[:provider],
              :uid => @authhash[:uid],
              :uname => @authhash[:name],
              :uemail => @authhash[:email],
              :token => @authhash[:token],
              :token_secret => @authhash[:token_secret],
              :token_refresh => @authhash[:token_refresh],
              :sf_consumer_key => @authhash[:sf_consumer_key],
              :sf_consumer_secret => @authhash[:sf_consumer_secret]
            )
            flash[:notice] = 'Your ' + @authhash[:provider].capitalize + ' account has been added for signing in at this site.'
            logger.info("---> Current_user add a new service. #{@authhash[:provider]}")
            redirect_to services_path
          end
        else
          if auth
            # signin existing user
            # in the session his user id and the service id used for signing in is stored
            session[:user_id] = auth.user.id
            session[:service_id] = auth.id
          
            flash[:notice] = 'Signed in successfully via ' + @authhash[:provider].capitalize + '.'
            redirect_to root_url
          else
            # this is a new user; show signup; @authhash is available to the view and stored in the sesssion for creation of a new user
            session[:authhash] = @authhash
            render signup_services_path
          end
        end
      else

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_services_list.html.erb
<ul id="services_list">
  <!--<li><%= link_to "/auth/salesforce" do %><%= image_tag "chatter_64.png", :size => "64x64", :alt => "Chatter" %>Chatter<% end %></li>-->
  <li><%= link_to "/auth/forcedotcom" do %><%= image_tag "chatter_64.png", :size => "64x64", :alt => "Chatter" %>Chatter<% end %></li>
  <li><%= link_to "/auth/facebook" do %><%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>Facebook<% end %></li>
  <li><%= link_to "/auth/linked_in" do %><%= image_tag "linkedin_64.png", :size => "64x64", :alt => "LinkedIn" %>LinkedIn<% end %></li>
  <li><%= link_to "/auth/twitter" do %><%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>Twitter<% end %></li>
</ul>

app/views/services/index.html.erb
<section id="services_manage" class="services">

  <h1><%= link_to "Go to Home page - to post a news", root_path %> </h1>
  <h1>Authentication Services - Settings</h1>

  <div style="float: left" id="auth_services">
    <h2>You can use these accounts to sign in</h2>

    <% @services.each do |service| %>
      <div class="service_in_use round">
        <div class="service_img">
          <% if ['aol', 'facebook', 'github', 'google', 'openid', 'twitter', 'yahoo'].index(service.provider) %>
            <%= image_tag "#{service.provider}_64.png", :size => "64x64" %>
          <%elsif ['linked_in'].index(service.provider) %>
            <%= image_tag "linkedin_64.png", :size => "64x64" %>

            <!-- todo replace with Chatter Icon -->
          <%elsif ['chatter', 'forcedotcom'].index(service.provider) %>
            <%= image_tag "chatter_64.png", :size => "64x64" %>
          <% else%>
            <%= image_tag "openid_64.png", :size => "64x64" %>
          <% end %>
        </div>

        <div class="service_userdata">
          <% if service.uid.starts_with?('http') %>
            <%= service.uid.scan(/http[s]*:\/\/.*?\//)[0] %>
          <% else %>
            <%= service.provider.capitalize %>: <%= service.uid %>
          <% end %>
          <br />
          <%= service.uname if service.uname != '' %><br />
          <%= service.uemail if service.uemail != '' %><br />
          <% if session[:service_id] == service.id %>
            <span>Signed in</span>
          <% else %>
            <%= link_to "Remove this service", service, :confirm => 'Are you sure you want to remove this authentication?', :method => :delete, :class => "remove" %>
          <% end %>
        </div>
      </div>
    <% end %>


    <div id="services_available">
      <h2>You can connect more accounts to sign in</h2>

      <%= render 'services_list'%>
    </div>
  </div>

  <div style="text-align: left; display: block" id="wallpaper">
    <h2>Change My Wall Paper</h2>
    <div class="feedpost_box">
    <%= form_tag(setwallpaper_users_path, :method => "post") do %>
      <%= label_tag :wallpaper, "URL to new Wallpaper Image:" %>
      <%= url_field_tag :wallpaper, current_user.wallpaper, :size=>"50x3" %>
      <br/>
       <%= submit_tag("Update My Wall Paper", :align => 'right') %>
    </div>
    <%end%>

  </div>
</section>

app/views/services/signin.html.erb
<section id="services_signin" class="services">
  <h1>Sign in</h1>

  <p>
    You can sign up or sign in using one of your existing accounts at Chatter, Facebook, LinkedIn, and Twitter. Please select the provider you want to use:
  </p>

  <div>
    <%= render "services_list" %>
  </div>
</section>

app/views/services/signup.html.erb
<section id="services_new" class="services">
	<h1>New account</h1>

	<div>
		<h3>This authentication is new to Chouette Social</h3>
		
		<p class="small">
			Provider: <%= @authhash[:provider] %><br />
			ID: <%= @authhash[:uid] %><br />
			Name: <%= @authhash[:name] %><br />
			Email: <%= @authhash[:email] %>	<br />
		</p>

		<%= form_tag :controller => "services", :action => "newaccount" do %>
			<%= submit_tag "Confirm and create new account" %> <%= submit_tag "Cancel" %>
		<% end %>
	</div>

	<p>
	If you think you already have an Chouette Social account, and you were just trying to associate a new authentication with your existing account, then you’re in the wrong place. You’re not logged into Chouette Social right now.
	</p>

	<p class="small nomargin">
		If you have a Chouette Social account, and you’d like to associate another authentication with it, here’s what to do:
	</p>
	<ul class="small">
		<li>Log in in to Chouette Social with your existing authentication service TODO</li>
		<li>Go to your settings page (located at the top/right corner of the page)</li>
		<li>Add one or more accounts to be used to sign-in</li>
	</ul>
</section>