config/routes.rb
ChouetteSocial::Application.routes.draw do

  match "/signin" => "services#signin"
  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index] do
    collection do
      get 'test'
      post 'newfeedpost'
      get 'newfeedpost'
      post 'setwallpaper'
      get 'setwallpaper'
    end
  end
  
  resources :feedposts, :only => [:index] do
    collection do
      post 'add_new'
      get 'add_new'
    end
  end

  root :to => "users#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :services
  
  attr_accessible :name, :email, :wallpaper
end

app/controllers/users_controller.rb
require "twitter"
require 'linkedin'
require 'oauth'
require 'yaml'
require 'json'
require 'fb_graph'
require 'asf-rest-adapter'
require 'nokogiri'
require 'xmlsimple'

require Rails.root.to_s + '/app/helpers/application_helper.rb'

class UsersController < ApplicationController
  def index
    if !current_user
      puts 'you are NOT logged in'
    else
      puts 'you are signed in.'
      @my_services = current_user.services.find(:all)

      get_my_feeds
    end
  end

  def get_my_feeds
    chatter = current_user.services.find(:first, :conditions => { :provider => 'forcedotcom' })
    #salesforce = current_user.services.find(:first, :conditions => { :provider => 'salesforce' })
    facebook = current_user.services.find(:first, :conditions => { :provider => 'facebook' })
    lnk = current_user.services.find(:first, :conditions => { :provider => 'linked_in' })
    twitter = current_user.services.find(:first, :conditions => { :provider => 'twitter' })

    if twitter
      begin
        do_twitter_feeds
      rescue Exception => e
        unless flash[:error].nil?
          flash[:error] << "You Twitter services has a problem: #{e.message}. Consider remove & add this service again"
        else
          flash[:error] = "You Twitter services has a problem: #{e.message}. Consider remove & add this service again"
        end
      end
    end
    if lnk
      begin
        do_linked_in_feeds
      rescue Exception => e
        unless flash[:error].nil?
          flash[:error] << "You LinkedIn services has a problem: #{e.message}. Consider remove & add this service again"
        else
          flash[:error] = "You LinkedIn services has a problem: #{e.message}. Consider remove & add this service again"
        end
      end

    end
    if chatter
      begin
        do_chatter_feeds
      rescue Exception => e
        unless flash[:error].nil?
          flash[:error] << "You Chatter services has a problem: #{e.message}. Consider remove & add this service again"
        else
          flash[:error] = "You Chatter services has a problem: #{e.message}. Consider remove & add this service again"
        end
      end

    end
    if facebook
      begin
        do_fb_feeds
      rescue Exception => e
        unless flash[:error].nil?
          flash[:error] << "You Facebook services has a problem: #{e.message}. Consider remove & add this service again"
        else
          flash[:error] = "You Facebook services has a problem: #{e.message}. Consider remove & add this service again"
        end
      end

    end

  end

  def do_chatter_feeds
    auth = current_user.services.find(:first, :conditions => { :provider => 'forcedotcom' })
    #using refresh_token to generate a new access_token
    token_refresh = auth.token_refresh
    sf_consumer_key = auth.sf_consumer_key
    sf_consumer_secret = auth.sf_consumer_secret
    ct = ApplicationHelper::chatter_client(token_refresh, sf_consumer_key, sf_consumer_secret)

    @rest_svr = ct['instance_url']
    access_token = ct['access_token']
    # Because ct['id'] is in https://login.salesforce.com/id/Org_ID/User_ID format, trim it
    # https://login.salesforce.com/id/00DA0000000XpCkMAK/00ENV['default_feed_counts'].to_sA0000000S2C7IAK
    profile_id = ct['id'].gsub(/\S+\//mi, "")
    api_version=ENV['salesforce_rest_api'] # 'v21.0'
    header = { "Authorization" => "OAuth " + access_token, "content-Type" => 'application/json' }

    #ct_user = Salesforce::Rest::User.find(profile_id)

    query = "SELECT Id, CreatedDate, CreatedBy.Name, CreatedBy.Id, FeedPost.Id, FeedPost.Body from UserFeed where parentid='#{profile_id}' order by CreatedDate Desc limit #{ENV['default_feed_counts'].to_s}"
    @chatter_feeds = Salesforce::Rest::AsfRest.run_soql(query, header, @rest_svr, api_version)['records']

  end

  def do_twitter_feeds
    # My Twitter Feed
    auth = current_user.services.find(:first, :conditions => { :provider => 'twitter' })
    token = auth.token
    token_secret = auth.token_secret
    tc = ApplicationHelper::twitter_client(token, token_secret)

    # See doc http://rubydoc.info/gems/twitter/1.2.0/Twitter/Client/Timeline
    @twitter_feeds = tc.home_timeline({:count => ENV['default_feed_counts'].to_s})
  end
  
  def do_linked_in_feeds
    #linked In feeds
    auth = current_user.services.find(:first, :conditions => { :provider => 'linked_in' })
    token = auth.token
    token_secret = auth.token_secret
    lnk_client = ApplicationHelper::linkedin_client(token, token_secret)
    linked_in_profile = lnk_client.profile(:fields => ['first-name', 'last-name', 'headline', 'current-share'])
    network_feeds = lnk_client.network_updates({:count => ENV['default_feed_counts'].to_s, :scope => 'self'})
    #now parsing a Nokiri document
    @linked_in_feeds = XmlSimple.xml_in(network_feeds.instance_variable_get("@doc").to_s)['updates'][0]['update']    
  end

  def do_fb_feeds
    auth = current_user.services.find(:first, :conditions => { :provider => 'facebook' })
    token = auth.token
    token_secret = auth.token_secret
    fb = ApplicationHelper::fb_client(token)
    #a_user = FbGraph::User.fetch('id_please')
    @fb_feeds = fb.feed({:limit => ENV['default_feed_counts'].to_s})
  end

  def setwallpaper
    #current_user.update(:wallpaper => params[:wallpaper])
    current_user.update_attributes(:wallpaper => params[:wallpaper].to_s)
    flash[:notice] = "You wallpaper has been updated to use #{current_user.wallpaper}"
    redirect_to services_path
    return
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if !current_user %>
<h6 style="color: oldlace"><font style="color: crimson">Chouette-Social</font> is a Social Networking Feed Aggregator tool. You can get all your favorite newsfeeds in one place, e.g. Chatter, Facebook, Twitter, LinkedIn, ....</h6>
Source code will be available on <a href="http://github.com/raygao">Github</a> shortly under the Creative Common license.
  <br/>
  <h2 style="color: chartreuse">First, please Authenticate yourself --> <%= link_to "click here", signin_services_path %></h2>
<% else %>
  <div style="width:850px;">
    <h2>Welcome <%=current_user.name%>!</h2>
    <%= form_tag(add_new_feedposts_path, :method => "post") do %>
      <div class="alignCenter">
        <div class="feedpost_box">
          <%= label_tag :feed_update, "Feel free to say something:" %>
          <%= text_area_tag :feed_update, '', {:size => "80x3", :maxlength=>"140"} %>
        </div>
        <br/>

        <% for service in @my_services %>
          <%  if service.provider =='forcedotcom' %>
            <!-- using chatter for forcedotcom name -->
            <%= check_box_tag(service.provider) %>
            <%= label_tag(service.provider, "Chatter") %>
          <%else%>
            <%= check_box_tag(service.provider) %>
            <%= label_tag(service.provider, service.provider.camelize) %>
          <%end%>
        <%end %>
        <br/>
        <br/>
        <%= image_submit_tag("post_button.gif")%>
      </div>
    <% end %>
  </div>

  <hr/>


  <div class="coda-slider-wrapper" >
    <div class="coda-slider preload" id="coda-slider-1">

      <div class="panel">
        <div id="fb_feeds" class="panel-wrapper">
          <h2 class="title">Facebook</h2>
          <p>
            <% unless @fb_feeds.nil? || @fb_feeds.empty? %>
            <table CELLSPACING=10 cellpadding="10">
              <tr>
                <th>ID</th>
                <th>Message:</th>
                <th>Posted by:</th>
                <th>Created at:</th>
              </tr>
              <% i= 0 %>
              <% for fb_feed in @fb_feeds %>
                <tr>
                  <%begin%>
                    <td><%= i=i+1 %></td>
                    <td>
                      <%unless fb_feed.message.nil? ||fb_feed.message.empty?%>
                        <% fmessage = auto_link(fb_feed.message) %>
                        <%= raw fmessage %>
                      <%end%>
                    </td>
                    <td align="center">
                      <a href="http://www.facebook.com/profile.php?id=<%= fb_feed.from.identifier%>">
                        <img src="http://graph.facebook.com/<%= fb_feed.from.identifier%>/picture" />
                        <br/>
                        <%= fb_feed.from.name %>
                      </a>
                    </td>
                    <td><%= fb_feed.updated_time %> </td>
                  <%rescue Exception => e%>
                    <td colspan="4"> <%= e.message %></td>
                  <%end%>
                </tr>
              <%  end %>
            </table>
          <%end%>
          </p>
        </div>
      </div>

      <div class="panel">
        <div id="linkedins" class="panel-wrapper">
          <h2 class="title">LinkedIn</h2>
          <p>
            <% unless @linked_in_feeds.nil? || @linked_in_feeds.empty? %>
            <table CELLSPACING=10 cellpadding="10">
              <tr>
                <th>ID</th>
                <th>Message:</th>
                <th>Posted by:</th>
                <th>Created at:</th>
              </tr>
              <% i= 0 %>
              <% for lk_feed in @linked_in_feeds %>
                <tr>
                  <%begin%>
                    <td><%= i=i+1 %></td>
                    <td>
                      <% lmessage = auto_link(lk_feed['update-content'][0]['person'][0]['current-status'][0].to_s) %>
                      <%= raw lmessage%>
                    </td>
                    <td>
                      <a href ="<%= raw lk_feed['update-content'][0]['person'][0]['site-standard-profile-request'][0]['url'][0]%>">
                        <img src="<%= raw lk_feed['update-content'][0]['person'][0]['picture-url'][0]%>"/>
                        <br/>
                        <%= lk_feed['update-content'][0]['person'][0]['first-name'][0]%> <%= lk_feed['update-content'][0]['person'][0]['last-name'][0]%>
                      </a>
                    </td>
                    <td><%= Time.parse(lk_feed['timestamp'][0])%></td>
                  <%rescue Exception => e%>
                    <td colspan="2"> <%= e.message %></td>
                  <%end%>
                </tr>
              <%  end %>
            </table>
          <%end%>
          </p>
        </div>
      </div>


      <div class="panel">
        <div id="tweets" class="panel-wrapper">
          <h2 class="title">Tweets</h2>
          <p>
            <% unless @twitter_feeds.nil? || @twitter_feeds.empty? %>
            <table CELLSPACING=10 cellpadding="10">
              <tr>
                <th>ID</th>
                <th>Message:</th>
                <th>Posted by:</th>
                <th>Created at:</th>
              </tr>
              <% i= 0 %>
              <% for tw_feed in @twitter_feeds %>
                <tr>
                  <%begin%>
                    <td><%= i=i+1 %></td>                    
                    <td>
                      <% message = auto_link(tw_feed.text.to_s) %>
                      <%= raw parse_twitter(message)  %>
                    </td>
                    <td align="center">
                      <% url_to_profile = "http://twitter.com/#!/" + tw_feed.user.screen_name.to_s%>
                      <a href="<%= raw url_to_profile%>">
                        <img src="<%= tw_feed.user.profile_image_url.to_s%>"/>
                        <br/>
                        <%= tw_feed.user.name%>
                      </a>
                    </td>
                    <td><%= tw_feed.created_at.to_s%></td>
                  <% rescue Exception => e %>
                    <td colspan="2"> <%= e.message %></td>
                  <%end%>
                </tr>
              <%  end %>
            </table>
          <%end%>
          </p>
        </div>
      </div>

      <div class="panel">
        <div class="panel-wrapper" id="chatters">
          <h2 class="title">Chatter</h2>
          <p>
            <% unless @chatter_feeds.nil? || @chatter_feeds.empty? %>
            <table CELLSPACING=10 cellpadding="10">
              <tr>
                <th>ID</th>
                <th>Message:</th>
                <th>Posted by:</th>
                <th>Created at:</th>
              </tr>
              <% i= 0 %>
              <% for chatter in @chatter_feeds %>
                <tr>
                  <%begin%>
                    <td><%= i=i+1 %></td>                    
                    <td>
                      <% cmessage = auto_link(chatter['FeedPost']['Body'])%>
                      <%= raw cmessage%>
                    </td>
                    <td align="center">
                      <a href="<%= @rest_svr + "/" + chatter['CreatedBy']['Id']%>"><%= chatter['CreatedBy']['Name']%></a>
                    </td>
                    <td><%= chatter['CreatedDate']%></td>
                  </tr>
                <%rescue Exception => e%>
                  <td colspan="4"> <%= e.message %></td>
                <%end%>
              <%  end %>
            </table>
          <%end%>
          </p>
        </div>
      </div>


    </div>
  </div>

<%end%>

app/views/users/test.html.erb
This page can be viewed by authenticated users only! <%= link_to "Click here", users_path %> to return to the main page.